### ISSUE TITLE
compat_resource polluting chefspec runs

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/compat_resource#106] opened 2016-09-16 17:22 UTC
We're still getting tons of warnings when running chefspec even on the latest compat_resource cookbooks:

```
    installs package iptables
  rhel 7
/var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chefspec20160916-48778-1f2dp6kfile_cache_path/cookbooks/compat_resource/libraries/autoload.rb:24: warning: already initialized constant ChefCompat::Resource
/var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chefspec20160916-48778-1f2dp6kfile_cache_path/cookbooks/compat_resource/libraries/autoload.rb:24: warning: previous definition of Resource was here
/var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chefspec20160916-48778-1f2dp6kfile_cache_path/cookbooks/compat_resource/libraries/autoload.rb:26: warning: already initialized constant ChefCompat::Mixin::Properties
/var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chefspec20160916-48778-1f2dp6kfile_cache_path/cookbooks/compat_resource/libraries/autoload.rb:26: warning: previous definition of Properties was here
    should install iptables-services
/var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chefspec20160916-48778-1f2dp6kfile_cache_path/cookbooks/compat_resource/libraries/autoload.rb:24: warning: already initialized constant ChefCompat::Resource
/var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chefspec20160916-48778-1f2dp6kfile_cache_path/cookbooks/compat_resource/libraries/autoload.rb:24: warning: previous definition of Resource was here
/var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chefspec20160916-48778-1f2dp6kfile_cache_path/cookbooks/compat_resource/libraries/autoload.rb:26: warning: already initialized constant ChefCompat::Mixin::Properties
/var/folders/wd/dzkzgh7d4_74484kpjky6ctc0000gn/T/chefspec20160916-48778-1f2dp6kfile_cache_path/cookbooks/compat_resource/libraries/autoload.rb:26: warning: previous definition of Properties was here
    disables and stops iptables service
```

**Comment by lamont-granquist** [comment] 2016-09-20 17:10
should be closed by #108

**Comment by jsmartt** [comment] 2016-09-22 17:25
@lamont-granquist , I'm still seeing these messages on v12.14.6. When I changed [this](https://github.com/chef-cookbooks/compat_resource/blob/v12.14.6/libraries/autoload.rb#L23) line from

```ruby
unless defined?(Chef::Compat::Resource) && defined?(ChefCompat::Mixin::Properties)
```

 to

```ruby
unless defined?(ChefCompat::Resource) && defined?(ChefCompat::Mixin::Properties)
```
that stopped the warnings. Is that what was intended, or does that just happen to work?

**Comment by lamont-granquist** [comment] 2016-09-23 01:48
that is what was intended

**Closed** 2016-09-26 17:28 UTC
